plugins {
    id 'fabric-loom' version '1.14-SNAPSHOT'
    id "idea"
    id "maven-publish"
}

group 'info.journeymap'

/* Artifact Version */
version = "${project.api_version}-${project.minecraft_version}"
if (project.snapshot) {
    version = version + "-SNAPSHOT"
}

def baseName = "${project.base_name}" + "-fabric"
base.archivesName = baseName

boolean localBuild = (hasProperty("buildProfile") && "local".equals(property("buildProfile")))

configurations {
    testmodImplementation.extendsFrom implementation
}

//sourceCompatibility = JavaVersion.VERSION_21
//targetCompatibility = JavaVersion.VERSION_21

repositories {
    maven {
        url "https://www.cursemaven.com"
    }
}

java {
    toolchain.languageVersion = JavaLanguageVersion.of(21)
    withSourcesJar()
    withJavadocJar()
}
/* Use the same compile and runtime classpath in the Example Mod */
//sourceSets {
//    testmod {
//        compileClasspath += main.compileClasspath
//        runtimeClasspath += main.runtimeClasspath
//    }
//}

loom {
    runs {
        client {
            client()
            setConfigName("Fabric Client")
            ideConfigGenerated(true)
            runDir("run/client")
            programArg("--username=Dev")
        }
        server {
            server()
            setConfigName("Fabric Server")
            ideConfigGenerated(true)
            runDir("run/server")
        }
    }
}

dependencies {
    minecraft "com.mojang:minecraft:${project.minecraft_version}"
    mappings loom.layered() {
        officialMojangMappings()
    }
    modImplementation "net.fabricmc:fabric-loader:${project.fabric_loader_version}"
    modImplementation "net.fabricmc.fabric-api:fabric-api:${project.fabric_api_version}"

    // for annotations
    implementation group: 'com.google.code.findbugs', name: 'jsr305', version: '3.0.1'

    compileOnly project(":common")
    testmodImplementation sourceSets.main.output
}
/* Replace tokens in resources files */
processResources
        {
            duplicatesStrategy = DuplicatesStrategy.INCLUDE
            // this will ensure that this task is redone when the versions change.
            inputs.property "version", project.version
            inputs.property "mcversion", project.minecraft_version

            // replace stuff in mcmod.info on copy
            filesMatching("fabric.mod.json") {
                expand 'version': project.version, 'mcversion': project.minecraft_version
            }
        }



tasks.withType(JavaCompile).configureEach {
    source(project(":common").sourceSets.main.allSource)
    options.encoding = "UTF-8"
}

tasks.withType(Javadoc).configureEach {
    source(project(":common").sourceSets.main.allJava)
}

tasks.named("sourcesJar", Jar) {
    from(project(":common").sourceSets.main.allSource)
}

/* Add our attributes to every Jar task */
jar {
    manifest {
        attributes = [
                "Manifest-Version"      : "1.0",
                "Implementation-Title"  : project.title,
                "Implementation-Version": project.version,
                "Implementation-URL"    : project.git_website
        ]
    }
}

/* Javadoc properties */
javadoc {
    title = project.title_javadoc
}

publishing {
    repositories {

        if (localBuild) {
            repositories {
                maven {
                    url System.getenv("local_maven_url") // or `url "file://" + System.getenv("local_maven")`
                }
            }
        } else {
            maven {
                name = "JourneyMap"
                url = uri("https://jm.gserv.me/repository/maven-snapshots/")

                credentials {
                    username = project.findProperty("journeymap.user") ?: System.getenv("JOURNEYMAP_USER")
                    password = project.findProperty("journeymap.password") ?: System.getenv("JOURNEYMAP_PASSWORD")
                }

                version = project.version
            }
        }

    }

    publications {
        maven(MavenPublication) {
            groupId project.group
            artifactId baseName
            version project.version

            from(components["java"])
        }
    }
}
