modLoader = "javafml"
loaderVersion = "[1,)"
issueTrackerURL = "https://github.com/TeamJM/journeymap-api/issues"
[[mods]]
modId = "examplemod"
version = "${version}"
displayName = "Example for JourneyMap API"
displayURL = "http://journeymap.info"
authors = "Techbrew, Mysticdrew"
description = '''
Example mod showing how to write a plugin for the JourneyMap API.
'''

[[dependencies.examplemod]]
modId = "neoforge"
type = "required"
versionRange = "[0,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.examplemod]]
modId = "minecraft"
type = "required"
versionRange = "[${minecraft_version},)"
ordering = "NONE"
side = "BOTH"
