modLoader="javafml"
loaderVersion="[38,)"
issueTrackerURL="http://my.issue.tracker/" #optional
[[mods]]
modId="examplemodjm" #mandatory
version="1.8" #mandatory

displayName="Example for JourneyMap API" #mandatory
displayURL="http://journeymap.info" #optional
credits="Thanks for this example mod goes to Java" #optional
authors="Techbrew, Mysticdrew" #optional

description='''
Example mod showing how to write a plugin for the JourneyMap API.
'''
