plugins {
    id 'multiloader-loader'
    id 'net.minecraftforge.gradle' version '[7.0.11,8.0)'
}

repositories {
    maven minecraft.mavenizer
    maven fg.forgeMaven
    maven fg.minecraftLibsMaven
    maven { url "https://repo.spongepowered.org/maven" }
}

def baseName = "${project.mod_name}" + "-forge"
base.archivesName = baseName

/* ForgeGradle spec for Minecraft */
minecraft {
    mappings channel: 'official', version: minecraft_version

    runs {
        register('client') {
            workingDir.convention layout.projectDirectory.dir('run')
            mods {
                register('examplemod') {
                    source sourceSets.testmod
                }
            }
        }

        register('server') {
            workingDir.convention layout.projectDirectory.dir('run')
            args '--nogui'
            mods {
                register('examplemod') {
                    source sourceSets.testmod
                }
            }
        }
    }
}
sourceSets.main.resources.srcDir 'src/generated/resources'

dependencies {
    implementation minecraft.dependency("net.minecraftforge:forge:${minecraft_version}-${forge_version}")
    testmodImplementation sourceSets.main.output
}
sourceSets.each {
    def dir = layout.buildDirectory.dir("sourcesSets/$it.name")
    it.output.resourcesDir = dir
    it.java.destinationDirectory = dir
}

// Implement mcgradleconventions loader attribute
def loaderAttribute = Attribute.of('io.github.mcgradleconventions.loader', String)
['apiElements', 'runtimeElements', 'sourcesElements', 'javadocElements'].each { variant ->
    configurations.named("$variant") {
        attributes {
            attribute(loaderAttribute, 'forge')
        }
    }
}

sourceSets.configureEach {
    [it.compileClasspathConfigurationName, it.runtimeClasspathConfigurationName].each { variant ->
        configurations.named("$variant") {
            attributes {
                attribute(loaderAttribute, 'forge')
            }
        }
    }
}
