/*
 * JourneyMap API (http://journeymap.info)
 * http://github.com/TeamJM/journeymap-api
 *
 * Copyright (c) 2011-2016 Techbrew.  All Rights Reserved.
 * The following limited rights are granted to you:
 *
 * You MAY:
 *  + Write your own code that uses the API source code in journeymap.* packages as a dependency.
 *  + Write and distribute your own code that uses, modifies, or extends the example source code in example.* packages
 *  + Fork and modify any source code for the purpose of submitting Pull Requests to the TeamJM/journeymap-api repository.
 *    Submitting new or modified code to the repository means that you are granting Techbrew all rights to the submitted code.
 *
 * You MAY NOT:
 *  - Distribute source code or classes (whether modified or not) from journeymap.* packages.
 *  - Submit any code to the TeamJM/journeymap-api repository with a different license than this one.
 *  - Use code or artifacts from the repository in any way not explicitly granted by this license.
 *
 */
plugins {
    id "java-library"
    id "idea"
    id 'net.neoforged.moddev'
    id "maven-publish"
}

group 'info.journeymap'


/* Artifact Version */
version = "${project.api_version}-${project.minecraft_version}"
if (project.snapshot) {
    version = version + "-SNAPSHOT"
}
archivesBaseName = "${project.mod_name}" + "-neoforge"
def modVersion = project.api_version

configurations {
    testmodImplementation.extendsFrom implementation
}

/* Use the same compile and runtime classpath in the Example Mod */
sourceSets {
    testmod {
        compileClasspath += main.compileClasspath
        runtimeClasspath += main.runtimeClasspath
    }
}

repositories {
    maven {
        url "https://www.cursemaven.com"
    }
}

tasks.named("test").configure {
    enabled = false
}

dependencies {
//    implementation "net.neoforged:neoforge:${project.neoforge_version}"
    runtimeOnly "curse.maven:journeymap-${project.jm_project_id}:${project.forge_jm_file_id}"

    compileOnly project(":common")
    testmodImplementation sourceSets.main.output
}

/* Replace tokens in resources files */
processResources {
    duplicatesStrategy = DuplicatesStrategy.INCLUDE
    // this will ensure that this task is redone when the versions change.
    inputs.property "version", project.version
    inputs.property "mcversion", project.minecraft_version

    // replace stuff in neoforge.mods.toml on copy
    from(sourceSets.main.resources.srcDirs) {
        include 'META-INF/neoforge.mods.toml'
        expand 'version': project.version,
                'mcversion': project.minecraft_version,
                'modVersion': modVersion
    }
}

neoForge {
    version = neoforge_version
    // Automatically enable neoforge AccessTransformers if the file exists
    def at = project(':common').file('src/main/resources/META-INF/accesstransformer.cfg')
    if (at.exists()) {
        accessTransformers.add(at.absolutePath)
    }
    addModdingDependenciesTo(sourceSets["test"])
    parchment {
        minecraftVersion = mappings_mc_version
        mappingsVersion = mappings_date
    }
    runs {
        configureEach {
//            systemProperty('neoforge.enabledGameTestNamespaces', mod_id)
            ideName = "NeoForge ${it.name.capitalize()} (${project.path})" // Unify the run config names with fabric
            jvmArgument("-Dmixin.debug.export=true")
        }
        client {
            client()
            gameDirectory = project.file('run/client')
        }
        server {
            server()
            gameDirectory = project.file("run/server")
        }
    }
    mods {
        "${mod_id}" {
            sourceSet sourceSets.main
        }
    }
}

tasks.withType(JavaCompile).configureEach {
    source(project(":common").sourceSets.main.allSource)
}

jar {
    manifest {
        attributes = ["Manifest-Version"      : "1.0",
                      "Implementation-Title"  : project.title,
                      "Implementation-Version": project.version,
                      "Implementation-URL"    : project.git_website]
    }
}

/* Javadoc properties */
javadoc {
    title = project.title_javadoc
}

tasks.withType(Javadoc).configureEach {
    source(project(":common").sourceSets.main.allJava)
}
tasks.named("sourcesJar", Jar) {
    from(project(":common").sourceSets.main.allSource)
}

publishing {
    repositories {
        maven {
            name = "JourneyMap"
            url = uri("https://jm.gserv.me/repository/maven-snapshots/")

            credentials {
                username = project.findProperty("journeymap.user") ?: System.getenv("JOURNEYMAP_USER")
                password = project.findProperty("journeymap.password") ?: System.getenv("JOURNEYMAP_PASSWORD")
            }

            version = project.version
        }
    }

    publications {
        maven(MavenPublication) {
            groupId project.group
            artifactId project.archivesBaseName
            version project.version
            artifact jar

            artifact project.sourcesJar {
                archiveClassifier.set("sources")
            }

            artifact project.javadocJar {
                archiveClassifier.set("javadoc")
            }
        }
    }
}
