name: ExampleJourneyMapPaperAddon
version: ${version}
main: example.paper.ExampleJourneyMapPaperAddon
api-version: '26.1.2'
author: ${mod_author}
description: Example JourneyMap API addon for Paper.
load: STARTUP
dependencies:
  server:
    journeymap:
      load: BEFORE
      required: true
      join-classpath: true
