name: 1.18.2_1.8-fabric

on:
  push:
    branches:
      - '1.18.2_1.8-fabric'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: Set up Java
        uses: actions/setup-java@v1
        with:
          version: 17

      - name: Gradle GenSources
        run: /bin/sh ./gradlew genSources

      - name: Gradle Build
        run: /bin/sh ./gradlew build

      - name: Gradle Publish
        run: /bin/sh ./gradlew -Pjourneymap.user=${{ secrets.JOURNEYMAP_USER }} -Pjourneymap.password=${{ secrets.JOURNEYMAP_PASSWORD }} publish
