name: CI

on:
  push:
    branches-ignore:
      - 'master'
      - '1.18.1_1.8'
      - '1.17.1_1.8'
      - '1.16.5_1.8'
      - '1.19.x_1.8'

  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: Set up Java
      uses: actions/setup-java@v1
      with:
        version: 16

    - name: Gradle Build
      run: /bin/sh ./gradlew build
