name: CI

on:
  push:
    branches-ignore:
      - 'master'
      - '1.19.3_1.9-fabric'
      - '1.19.3_1.9-forge'

  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: Set up Java
      uses: actions/setup-java@v1
      with:
        version: 17

    - name: Gradle Build
      run: /bin/sh ./gradlew build
